// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

/**
 * Prisma CLI configuration (Prisma 7 keeps this file separate from the
 * schema; `prisma init` scaffolds it as `prisma7.config.ts`).
 *
 * The datasource URL is deliberately NOT in prisma/schema.prisma — it is
 * resolved here, from the environment.
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
